name: build

on: push

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cmake build instruction should work
        run: |
          mkdir _build
          cd _build
          cmake ..
          make -j2 
          ./quiver -h
